version: '3'
services:
  nginx:
    build:
      context: ./
      dockerfile: docker/nginx.docker
    volumes:
      - ./:/var/www
    ports:
      - "8080:80"
    links:
      - app

  app:
    build:
      context: ./
      dockerfile: docker/php.docker
    volumes:
      - ./:/var/www
    links:
      - mysql
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
    working_dir: /var/www
    tty: true

  mysql:
    image: mysql:5.7
    volumes:
      -  ./docker/mysql/init:/docker-entrypoint-initdb.d
      - ./storage/docker/mysql:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_USER=app"
      - "MYSQL_PASSWORD=blog"
      - "MYSQL_DATABASE=blog"
    ports:
      - "33061:3306"
